export const ThemeColors = {
  default: {
    s_app_header_bg: "#ffffff",
    s_category_header: "#1D1F22",
    s_card_title: "#1d1f22",
    s_card_title_out_of_stock: "#8D8F9A",
    s_header_nav_link: "#1D1F22",
    s_header_nav_link_active: "#5ece7b",
    s_cart_title: "#1d1f22",
    s_cart_border: "#E5E5E5;",
    s_dropdown: "#f9f9f9",
    s_currency_hover: "#f1f1f1",
    s_cart_icon_counter_inner: "#ffffff",
    s_cart_icon_counter_outer: "#1d1f22",
    s_card_cart_button: "#5ece7b",
    s_card_cart_button_hover: "#4caf50",
    s_out_of_stock_title: "#8d8f9a",
    s_card_border_hover: "#a8acb030",
    s_order_add_to_cart_button: "#5ece7b",
    s_size_button: "#ffffff",
    s_size_button_text: "#000000",
    s_size_button_hover: "#000000",
    s_size_button_text_hover: "#ffffff",
    s_color_button_border: "#5ece7b",
    s_color_button_outline: "ffffff",
    s_mini_cart_background: "#FFFFFF",
    s_mini_cart_backdrop: "#393748",
    s_view_bag_button: "#ffffff",
    s_disabled_button: "#cccccc",
  },
};
